protect 'add-on' and 'add on' from tokenization
mozilla/kitsune pull request #4663
Opened 2021-02-02 12:16 UTC by LeoMcA

https://github.com/mozilla/sumo-project/issues/748

a nice side-effect is this causes "add-ons" to be highlighted properly in search results, before:

![Screenshot_2021-02-02 Mozilla Support - 127 0 0 1](https://user-images.githubusercontent.com/755354/106598893-45563a00-6550-11eb-99cc-d7fd5410e445.png)

after:

![Screenshot_2021-02-02 Mozilla Support - 127 0 0 1(2)](https://user-images.githubusercontent.com/755354/106599044-733b7e80-6550-11eb-8c6d-8f84078658a4.png)

2021-02-03 15:06 UTC, akatsoulas requested changes

2021-02-03 15:06 UTC, akatsoulas commented on kitsune/search/v2/es7_utils.py
> +            prefix = locale
The first argument of this function is accepting a locale. With this optimization you basically adapt a new naming schema by passing the name of the default analyzer as a locale. Personally I believe that the complexity introduced counteracts the benefits. In any case though we should not treat the analyzers name as a locale

2021-02-03 15:06 UTC, akatsoulas commented on kitsune/search/v2/es7_utils.py
> +            prefix = locale
To be clear, I am not against having a default name where applicable for our filters but how we are doing it should be more straightforward

2021-02-04 17:28 UTC, LeoMcA commented
Closing, as code has been merged into https://github.com/mozilla/kitsune/pull/4666, and comments here should be addressed there.

2021-02-04 17:28 UTC, closed without merging