Make it possible to update step labels via wizard manager
mozilla/kitsune pull request #5518
Opened 2023-05-24 19:31 UTC by hannajones

This is a fix for [the issue](https://github.com/mozilla/sumo/issues/1316) identified by @emilghittasv where the step indicator label doesn't change based on sign in state.

The fix ended up being a little more involved since we basically need to be able to pass data about the steps themselves when state changes. Previously we only passed that kind of step data to the wizard to initialize the steps, so it wasn't intended to be dynamic.

2023-05-25 16:03 UTC, mikeconley requested changes
This works, but I think it misses a case - when I was testing this signed into SUMO, it did properly update the Step 1 label. After I signed into FxA though and was redirected back to the page, Step 1 was labelled "Create an account" despite being signed in:

![image](https://github.com/mozilla/kitsune/assets/195042/a8d3dcf8-039a-478f-a599-37f535e54812)

So I think we might have to take into account - that we might want the Step 1 label updated even if it's not the currently active step.

2023-05-25 18:36 UTC, hannajones commented
@mikeconley poking around at this and I found a different bug that's a bit more severe - when I'm not logged in to SUMO the second step always shows as "unavailable." I think it has something to do with the order in which we receive updates and the fact that we don't update the step `status` in `switching-device-wizard-maanger.js`, so when we pass metadata to `<form-wizard>.setStep` we're always overwriting the `status` to `unavailable` 😞

Might go back to the drawing board on this one and see if there's a more straightforward way to just change the labels.

<img width="900" alt="Screenshot 2023-05-25 at 2 35 35 PM" src="https://github.com/mozilla/kitsune/assets/15138046/d4081060-646b-4e4b-b967-18c071347c85">

2023-05-25 19:31 UTC, hannajones commented
@mikeconley got this working, but it definitely feels pretty clunky 😕 Going to keep looking to see if I can find something simpler, definitely open to suggestions here

2023-05-26 14:45 UTC, mikeconley approved these changes
This works brilliantly. Much cleaner. Thanks so much, @hannajones!

2023-05-26 14:45 UTC, merged