Main navigation update
mozilla/kitsune pull request #5644
Opened 2023-09-13 13:11 UTC by smithellis

Main navigation additions
Name change to Mozilla Accounts

2023-09-13 14:43 UTC, akatsoulas requested changes

2023-09-13 14:43 UTC, akatsoulas commented on kitsune/sumo/jinja2/includes/common_macros.html
> -{% macro survey_cta_banner() %}
Why are you removing this?

2023-10-04 21:23 UTC, smithellis commented
This should be ready for another look @akatsoulas

2023-10-12 11:46 UTC, akatsoulas approved these changes

2023-10-12 11:46 UTC, merged