Add users and groups as part of generatedata.py
mozilla/kitsune pull request #5968
Opened 2024-04-21 23:54 UTC by smithellis

Creates group with int number of users
* staff: 15
* small_group: 10
* medium_group: 15
* large_group: 1000
* xlarge_group: 5000

All usernames will start with group name for easy testing Usernames are a concatenation of [group name]+User+count
* Example: small_groupUser1, medium_groupUser10, etc.

2024-06-05 13:20 UTC, akatsoulas commented
@smithellis is this still relevant/valid?

2024-06-05 13:45 UTC, smithellis commented
I think this was a casual Friday bit of work. I like it and find it useful, but if you don't, feel free to close. Stemmed from having the messaging work and needing to test with various group sizes.

2024-06-07 03:08 UTC, akatsoulas commented
In that case, personally I would use the test factories for User and Groups. Please also move this under the `scripts`  folder under the root level of the repo. Let me know when it's ready for a final pass

2024-08-02 14:50 UTC, smithellis commented
I moved this to scripts - not sure what you were saying about the factories? They are in use. Did you mean to modify factories or add to factories or...?

2024-09-03 11:17 UTC, akatsoulas requested changes

2024-09-03 11:17 UTC, akatsoulas commented on scripts/generate_users_and_groups.py
> +            u = UserFactory(username=user_name, groups=[g])
This should be enough to create the user without the need to call the `save()` method

2024-09-03 11:17 UTC, akatsoulas commented on scripts/generate_users_and_groups.py
> +        g = GroupFactory(name=group_name)
This should be enough to create the group without the need to call the `save()` method

2024-09-03 11:17 UTC, akatsoulas commented on scripts/generate_users_and_groups.py
> +        g = GroupFactory(name=group_name)
GroupFactory.create(args)

2024-09-03 11:17 UTC, akatsoulas commented on scripts/generate_users_and_groups.py
> +def generate_sampledata(options):
is the `options` used anywhere?

2024-09-03 11:17 UTC, akatsoulas commented on scripts/generate_users_and_groups.py
> +        for _ in range(user_count):
You can use UserFactory.create_batch(size, ...

2024-10-14 08:52 UTC, akatsoulas commented
Closing this as stale. Please reopen if it's still relevant.

2024-10-14 08:52 UTC, closed without merging