Populate username by default
mozilla/kitsune pull request #6001
Opened 2024-05-13 10:58 UTC by akatsoulas

2024-05-13 19:02 UTC, smithellis requested changes

2024-05-13 19:02 UTC, smithellis commented on kitsune/sumo/form_fields.py
> +                raise ValidationError(_(f"{value} is not a valud username."))
Typo - "valid"

2024-05-14 10:10 UTC, akatsoulas commented on kitsune/sumo/form_fields.py
> +                raise ValidationError(_(f"{value} is not a valud username."))
updated!

2024-05-14 10:37 UTC, smithellis commented
Assuming that was a test hiccup, I'm good with this. I'll drop https://github.com/mozilla/kitsune/pull/5998

2024-05-14 11:27 UTC, merged