Add GA4 attributes to new nav
mozilla/kitsune pull request #6078
Opened 2024-06-19 14:57 UTC by akatsoulas

2024-06-20 20:57 UTC, escattone requested changes

2024-06-20 20:57 UTC, escattone commented on kitsune/sumo/jinja2/includes/common_macros.html
> +                   data-event-category="navigation" data-event-action="main navigation" data-event-label="protect-your-privacy">
```suggestion
                  data-event-name="link_click"
                  data-event-parameters='{
                    "link_name": "main-menu.topic-home",
                    "link_detail": "protect-your-privacy"
                  }'>
```

2024-06-20 20:57 UTC, escattone commented on kitsune/sumo/jinja2/includes/common_macros.html
> +                   data-event-category="navigation" data-event-action="main navigation" data-event-label="customize-settings-and-preferences">
```suggestion
                  data-event-name="link_click"
                  data-event-parameters='{
                    "link_name": "main-menu.topic-home",
                    "link_detail": "customize-settings-and-preferences"
                  }'>
```

2024-06-20 20:57 UTC, escattone commented on kitsune/sumo/jinja2/includes/common_macros.html
> +                   data-event-category="navigation" data-event-action="main navigation" data-event-label="install-and-update">
```suggestion
                  data-event-name="link_click"
                  data-event-parameters='{
                    "link_name": "main-menu.topic-home",
                    "link_detail": "install-and-update"
                  }'>
```

2024-06-20 20:57 UTC, escattone commented on kitsune/sumo/jinja2/includes/common_macros.html
> +                   data-event-category="navigation" data-event-action="main navigation" data-event-label="install-and-manage-add-ons">
```suggestion
                  data-event-name="link_click"
                  data-event-parameters='{
                    "link_name": "main-menu.topic-home",
                    "link_detail": "install-and-manage-add-ons"
                  }'>
```

2024-06-20 20:57 UTC, escattone commented on kitsune/sumo/jinja2/includes/common_macros.html
> +                   data-event-category="navigation" data-event-action="main navigation" data-event-label="emails">
```suggestion
                  data-event-name="link_click"
                  data-event-parameters='{
                    "link_name": "main-menu.topic-home",
                    "link_detail": "emails"
                  }'>
```

2024-06-20 20:57 UTC, escattone commented on kitsune/sumo/jinja2/includes/common_macros.html
> +                    "link_name": "main-menu.question-list",
If we want to be consistent with what I've done before for the `link_name` parameter, we should use either `main-menu.{slugified text of menu item}.{content_group of target}` or `main-menu.{content_group of target}` -- so maybe we should adjust this to:

```suggestion
                    "link_name": "main-menu.support-forum-home",
```

2024-06-20 20:57 UTC, escattone commented on kitsune/sumo/jinja2/includes/common_macros.html
> +                    "link_name": "main-menu.question-list",
```suggestion
                    "link_name": "main-menu.support-forum-home",
```

2024-06-20 20:57 UTC, escattone commented on kitsune/sumo/jinja2/includes/common_macros.html
> +                    "link_name": "main-menu.question-list",
```suggestion
                    "link_name": "main-menu.support-forum-home",
```

2024-06-20 20:57 UTC, escattone commented on kitsune/sumo/jinja2/includes/common_macros.html
> +                    "link_name": "main-menu.question-list",
```suggestion
                    "link_name": "main-menu.support-forum-home",
```

2024-06-20 20:57 UTC, escattone commented on kitsune/sumo/jinja2/includes/common_macros.html
> +                    "link_name": "main-menu.question-list",
```suggestion
                    "link_name": "main-menu.support-forum-home",
```

2024-06-20 20:57 UTC, escattone commented on kitsune/sumo/jinja2/includes/common_macros.html
> +                    "link_name": "main-menu.question-list",
```suggestion
                    "link_name": "main-menu.support-forum-home",
```

2024-06-20 20:57 UTC, escattone commented on kitsune/sumo/jinja2/includes/common_macros.html
> +                    "link_name": "main-menu.question-list",
```suggestion
                    "link_name": "main-menu.support-forum-home",
```

2024-06-20 20:57 UTC, escattone commented on kitsune/sumo/jinja2/includes/common_macros.html
> +                    "link_name": "main-menu.question-list",
```suggestion
                    "link_name": "main-menu.support-forum-home",
```

2024-06-20 20:57 UTC, escattone commented on kitsune/sumo/jinja2/includes/common_macros.html
> +                    "link_name": "main-menu.question-list",
```suggestion
                    "link_name": "main-menu.support-forum-home",
```

2024-06-20 20:57 UTC, escattone commented on kitsune/sumo/jinja2/includes/common_macros.html
> +                    "link_name": "main-menu.question-list",
```suggestion
                    "link_name": "main-menu.support-forum-home",
```

2024-06-20 20:57 UTC, escattone commented on kitsune/sumo/jinja2/includes/common_macros.html
> +                    "link_name": "main-menu.question_list",
```suggestion
                    "link_name": "main-menu.support-forum-home",
```

2024-06-20 20:57 UTC, escattone commented on kitsune/sumo/jinja2/includes/common_macros.html
> +                    "link_name": "main-menu.question-list",
```suggestion
                    "link_name": "main-menu.support-forum-home",
```

2024-06-20 20:57 UTC, escattone commented on kitsune/sumo/jinja2/includes/common_macros.html
> +                    "link_detail": "manage-preferences-and-and-ons"
Do we want to use `customize-settings-and-preferences` instead, since I think that's what we'll eventually arrive at right?

2024-06-21 09:29 UTC, akatsoulas commented
Most probably this won't cause any breakage as it has wording changes in link attributes and all the suggestions have been added, I am merging this to proceed with the testing

2024-06-21 09:30 UTC, merged