2021 - 500 Error after submission with no file
mozilla/kitsune pull request #6342
Opened 2024-11-08 19:07 UTC by smithellis

* Check for file, if none, return error message

2024-11-08 19:12 UTC, DevBeatDad commented
2021
500
6342

Sent from Proton Mail Android

-------- Original Message --------
On 11/8/24 21:08, smith  wrote:

> - Check for file, if none, return error message
>
> ---------------------------------------------------------------
>
> You can view, comment on, or merge this pull request online at:
>
> https://github.com/mozilla/kitsune/pull/6342
>
> Commit Summary
>
> - [1ef0446](https://github.com/mozilla/kitsune/pull/6342/commits/1ef0446b823d312477818b613693b7ccc9336b5f) 2021 - 500 Error after submission with no file
>
> File Changes
>
> ([1 file](https://github.com/mozilla/kitsune/pull/6342/files))
>
> -  M [kitsune/groups/views.py](https://github.com/mozilla/kitsune/pull/6342/files#diff-a5f805a1049653399efabed5b291d1beedb45714b7a4ca58294ceda1179702cf) (5)
>
> Patch Links:
>
> - https://github.com/mozilla/kitsune/pull/6342.patch
> - https://github.com/mozilla/kitsune/pull/6342.diff
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/mozilla/kitsune/pull/6342), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/ASBYSYDJLVD5WJAEEKGOAZTZ7UD3XAVCNFSM6AAAAABRODN5JOVHI2DSMVQWIX3LMV43ASLTON2WKOZSGY2DIOJRHAYTAMY).
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2024-11-11 10:08 UTC, akatsoulas requested changes

2024-11-11 10:08 UTC, akatsoulas commented on kitsune/groups/views.py
> +        if "avatar" not in request.FILES:
This should be moved to the clean method of the form. This way the `form.is_valid()` check will be erroneous and we won' have to add the next couple of lines.

2024-11-13 08:00 UTC, akatsoulas approved these changes

2024-11-13 08:00 UTC, merged