Create Tier3 of the taxonomy
mozilla/kitsune pull request #6362
Opened 2024-11-20 16:23 UTC by akatsoulas

2024-11-20 22:20 UTC, escattone requested changes

2024-11-21 09:54 UTC, akatsoulas commented on kitsune/products/migrations/0021_auto_20241120_0218.py
> +    },
I agree with you, I am going to raise this to the taxonomy meeting. We have a total of 9 tier 3 topics that are not associated with any product. My opinion is that we need to drop them. For now I am just keeping the code in sync with the mapping. I will update this either by removing the topics or by adding products

2024-11-21 10:01 UTC, akatsoulas commented on kitsune/products/migrations/0021_auto_20241120_0218.py
> +            continue
Good call, I moved the query at the top. This way we will skip the tier3 topic creation altogether if there's not a tier2 parent.

2024-11-21 10:03 UTC, akatsoulas commented
@escattone PR udpated

2024-11-21 18:04 UTC, escattone approved these changes
Just some typos to fix, and this is good to go! Thanks for this @akatsoulas !

2024-11-21 18:04 UTC, escattone commented on kitsune/products/migrations/0021_auto_20241120_0218.py
> +        "parent_slug": "site-brekages",
Typo.
```suggestion
        "parent_slug": "site-breakages",
```

2024-11-21 18:04 UTC, escattone commented on kitsune/products/migrations/0021_auto_20241120_0218.py
> +        "parent_slug": "site-brekages",
```suggestion
        "parent_slug": "site-breakages",
```

2024-11-21 18:04 UTC, escattone commented on kitsune/products/migrations/0021_auto_20241120_0218.py
> +        "parent_slug": "site-brekages",
```suggestion
        "parent_slug": "site-breakages",
```

2024-11-21 21:58 UTC, escattone commented on kitsune/products/migrations/0021_auto_20241120_0218.py
> +        "parent_slug": "site-brekages",
I added a commit to fix these typos.

2024-11-21 21:58 UTC, escattone commented on kitsune/products/migrations/0021_auto_20241120_0218.py
> +        "parent_slug": "site-brekages",
I added a commit to fix these typos.

2024-11-21 21:58 UTC, escattone commented on kitsune/products/migrations/0021_auto_20241120_0218.py
> +        "parent_slug": "site-brekages",
I added a commit to fix these typos.

2024-11-21 21:59 UTC, merged