Update KB helpful survey
mozilla/kitsune pull request #6423
Opened 2024-12-20 13:29 UTC by akatsoulas

2025-01-06 23:47 UTC, escattone requested changes
- When the user is not authenticated but has already voted anonymously, the voting form is still displayed when the article is viewed again, and if another vote is attempted, the response from the vote POST is a redirect to the KB article, which causes a strange article-within-an-article view of the page.

<img width="1383" alt="image" src="https://github.com/user-attachments/assets/c0211f0a-ac09-42b6-ba11-2999b119eaed" />

- The font size and weight of the `Yes` and `No` of the voting form should match those of its `Was this article helpful?` text.
    
<img width="270" alt="image" src="https://github.com/user-attachments/assets/be285bec-023c-4a39-aaa9-a5736cec3ea7" />

- When the user is authenticated, the voting form is pushed way down on the page.

<img width="1226" alt="image" src="https://github.com/user-attachments/assets/7b6af5da-9e69-4162-acfd-f8ba86e03db0" />

- The `Cancel` and `Submit` buttons of both the "yes" and "no" surveys are stacked instead of side-by-side.

<img width="367" alt="image" src="https://github.com/user-attachments/assets/3940767a-fdff-485e-905c-94e396977b6d" />

- When submitting the survey, the response is `Thanks for making us better!` instead of `Thanks for your feedback!` as the Figma indicates. Also, the text is not bold as is shown in Figma.

2025-01-08 11:12 UTC, akatsoulas commented
> The use of `htmx` and `alpine.js` is pretty cool!
> 
>     * The GA4 tracking events are not being generated (see comments in code below).
> 
>     * When the user is not authenticated but has already voted anonymously, the voting form is still displayed when the article is viewed again, and if another vote is attempted, the response from the vote POST is a redirect to the KB article, which causes a strange article-within-an-article view of the page.
> 
> 
> <img alt="image" width="1383" src="https://private-user-images.githubusercontent.com/3743693/400580011-c0211f0a-ac09-42b6-ba11-2999b119eaed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzMzM3NTgsIm5iZiI6MTczNjMzMzQ1OCwicGF0aCI6Ii8zNzQzNjkzLzQwMDU4MDAxMS1jMDIxMWYwYS1hYzA5LTQyYjYtYmExMS0yOTk5YjExOWVhZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDhUMTA1MDU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGQwNTdkNmRlNDNlMDAzNGUyNzFkOWNlNmNkNWYxNTY2ODI4OTM2MjNlM2M3NTkyZDlmZmE2ZGVjYzk2ZDgyYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2QsM3XwcB7CoCTE-etUkSe0oroU-goZbgY62U9iVqhc">
> 
>     * The font size and weight of the `Yes` and `No` of the voting form should match those of its `Was this article helpful?` text.
> 
> 
> <img alt="image" width="270" src="https://private-user-images.githubusercontent.com/3743693/400519065-be285bec-023c-4a39-aaa9-a5736cec3ea7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzMzM3NTgsIm5iZiI6MTczNjMzMzQ1OCwicGF0aCI6Ii8zNzQzNjkzLzQwMDUxOTA2NS1iZTI4NWJlYy0wMjNjLTRhMzktYWFhOS1hNTczNmNlYzNlYTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDhUMTA1MDU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODM1Nzg4YjM0ZDEzZjRjMGE1NTkzMWI1NDY5NTcyMzk3M2Y0ODU3MWUyMzIzZGI1YWU1YThlMWIxNjZjMjlhOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Tp2D0IGbgNBPWrF-hRaJPr81Y6lL4Ww_DJbSFqeJ9rY">

I am not sure about this. We treat the `Was this article helpful` as a header. I will follow up with Josh on this.
> 
>     * When the user is authenticated, the voting form is pushed way down on the page.
> 
It's actually the same space with the logged out view. The difference is that the editing tools push down the whole section
> 
>     * The `Cancel` and `Submit` buttons of both the "yes" and "no" surveys are stacked instead of side-by-side.

Have you tried a fresh build? It seems to be working for me
![image](https://github.com/user-attachments/assets/5ff1f5ef-ea72-445e-9642-f43116219043)

2025-01-08 15:55 UTC, escattone commented
> It's actually the same space with the logged out view. The difference is that the editing tools push down the whole section

Ah, I see that now, thanks. Ignore that comment! 😄 

Regarding the cancel and submit buttons of the survey, I did have a fresh build, but they're still always stacked for me. However, I noticed that your survey is wider than mine, so I guess the width of my survey is what is causing the buttons to stack. Hm, I'm not sure why my survey has a smaller width. Anyway, ignore that one too.

<img width="1303" alt="image" src="https://github.com/user-attachments/assets/93cb8253-bb65-4c0b-9413-32607e78aea6" />

2025-01-08 17:26 UTC, akatsoulas commented
> > It's actually the same space with the logged out view. The difference is that the editing tools push down the whole section
> 
> Ah, I see that now, thanks. Ignore that comment! 😄
> 
> Regarding the cancel and submit buttons of the survey, I did have a fresh build, but they're still always stacked for me. However, I noticed that your survey is wider than mine, so I guess the width of my survey is what is causing the buttons to stack. Hm, I'm not sure why my survey has a smaller width. Anyway, ignore that one too.

I will have another look to make sure that it scales properly to different screen sizes

2025-01-08 18:29 UTC, escattone reviewed
Overall, I really like the GA4-event-related changes, and when I tested them locally, the GA4 events are generated properly (except for the first comment below). I have two comments:
- After submitting a survey response, a final pair of `survey_opened` and `survey_closed` GA4 events are generated, because `survey_form.html` is rendered and returned for the `response_message` of `Thanks for your feedback!`. Both of those survey events include an empty `survey_type` parameter. See the image below. I'm thinking we shouldn't generate survey events in this case, because it'll misleadingly inflate the GA4 survey events.

<img width="629" alt="image" src="https://github.com/user-attachments/assets/d515138a-4e2e-4bb5-9ff5-e6f5ddf96bd9" />

- For the survey events, maybe we should use `article_survey_...` instead of `survey_...` to distinguish these events from any possible future survey events?

2025-01-08 18:32 UTC, escattone commented on kitsune/wiki/jinja2/wiki/includes/document_macros.html
> +            >{{ _('No') }}👎</button>
❤️

2025-01-09 16:39 UTC, escattone approved these changes
The GA4 events look good now. Just a indentation nit, and there's still the issue of the text of the `Yes👍` and `No👎` buttons looking different than the Figma designs (but as you said, you can discuss that with Josh). Thanks @akatsoulas!

2025-01-09 16:39 UTC, escattone commented on kitsune/wiki/jinja2/wiki/includes/survey_form.html
> +        }
Nit. The indentation is off.

2025-01-09 17:24 UTC, merged